ci: Change runner to self-hosted for auto-update

diff --git a/.github/workflows/autoupdate.yaml b/.github/workflows/autoupdate.yaml
--- a/.github/workflows/autoupdate.yaml
+++ b/.github/workflows/autoupdate.yaml
@@ -10,7 +10,7 @@ permissions:
 
 jobs:
   auto-update:
-    runs-on: ubuntu-latest
+    runs-on: [self-hosted, nixos]
 
     steps:
       - name: Checkout
@@ -18,11 +18,6 @@ jobs:
         with:
           ref: main
           fetch-depth: 0
-
-      - uses: NixOS/nix-installer-action@v1.0.0
-        with:
-          extra-conf: |
-            experimental-features = nix-command flakes pipe-operators
 
       - name: Configure Git
         run: |
@@ -65,11 +60,13 @@ jobs:
               args+=(--version=branch)
             fi
 
-            nix run nixpkgs#nix-update -- "${args[@]}" "$name" \
-              || echo "::warning::Failed to update $name"
+            nix-update "${args[@]}" "$name" || echo "::warning::Failed to update $name"
 
             echo "::endgroup::"
           done
+          
+      - name: Verify build before push
+        run: nix flake check
 
       - name: Push changes
         run: |
